#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SLE dimensionality sweep after unsupervised gene ranking.

Fixed scientific choices:
- experimental unit: donor
- gene ranking: donor-balanced variance
- no disease labels used
- candidate m values evaluated independently of classification

For each m, computes:
- gene-selection stability from existing ranking_stability.csv when available
- q_max = m / minimum donor cell count
- donor-level correlation-matrix rank, effective rank, min eigenvalue,
  max eigenvalue and condition number across ALL donors

The script reads the top-ranked genes from gene_rankings.csv generated by the
previous unsupervised audit. Expression is read from H5AD in backed mode.
"""

from __future__ import annotations
import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import scipy.sparse as sp
import anndata as ad


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--h5ad", type=Path, required=True)
    p.add_argument("--gene-selection-dir", type=Path, required=True)
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--donor-col", default="donor_id")
    p.add_argument("--m-values", default="128,160,192,224,256,288,320,336,352,368,384,400,416,432,448")
    p.add_argument("--target-sum", type=float, default=1e4)
    p.add_argument("--rank-tol", type=float, default=1e-10)
    p.add_argument("--eig-tol", type=float, default=1e-8)
    p.add_argument("--q-threshold", type=float, default=0.75)
    p.add_argument("--stability-threshold", type=float, default=0.90)
    p.add_argument("--condition-threshold", type=float, default=1e4)
    return p.parse_args()


def effective_rank(e):
    e = np.clip(np.asarray(e, float), 0, None)
    s = e.sum()
    if s <= 0:
        return 0.0
    p = e / s
    p = p[p > 0]
    return float(np.exp(-np.sum(p * np.log(p))))


def transform_counts(X, target_sum):
    if sp.issparse(X):
        X = X.tocsr().astype(np.float64)
        lib = np.asarray(X.sum(axis=1)).ravel()
        scale = np.divide(target_sum, lib, out=np.zeros_like(lib), where=lib > 0)
        Z = X.multiply(scale[:, None]).tocsr()
        Z.data = np.log1p(Z.data)
        return Z
    X = np.asarray(X, dtype=np.float64)
    lib = X.sum(axis=1)
    scale = np.divide(target_sum, lib, out=np.zeros_like(lib), where=lib > 0)
    return np.log1p(X * scale[:, None])


def main():
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    mvals = sorted({int(x) for x in args.m_values.split(",")})
    max_m = max(mvals)

    ranks = pd.read_csv(args.gene_selection_dir / "gene_rankings.csv")
    vr = ranks[ranks["method"] == "variance"].sort_values("rank")
    if len(vr) < max_m:
        raise ValueError(f"Only {len(vr)} variance-ranked genes available; need {max_m}")
    top_gene_indices = vr.iloc[:max_m]["gene_index"].to_numpy(dtype=int)

    a = ad.read_h5ad(args.h5ad, backed="r")
    if args.donor_col not in a.obs:
        raise KeyError(args.donor_col)
    if a.raw is None:
        raise ValueError("Expected raw counts in adata.raw")

    donors = a.obs[args.donor_col].astype("string")
    donor_names = pd.Index(pd.unique(donors))
    counts = donors.value_counts()
    nmin = int(counts.min())

    # Read columns in sorted order for HDF5 compatibility, then restore ranking.
    sorted_genes = np.sort(top_gene_indices)
    col_lookup = {g: j for j, g in enumerate(sorted_genes)}
    ranked_cols = np.array([col_lookup[g] for g in top_gene_indices], dtype=int)

    detail_rows = []
    for di, donor in enumerate(donor_names, start=1):
        row_idx = np.flatnonzero((donors == donor).to_numpy())
        X = a.raw.X[row_idx, sorted_genes]
        Z = transform_counts(X, args.target_sum)
        if sp.issparse(Z):
            Z = Z.toarray()
        Z = np.asarray(Z, dtype=np.float64)[:, ranked_cols]

        for m in mvals:
            Xm = Z[:, :m]
            sd = Xm.std(axis=0, ddof=1)
            valid = np.isfinite(sd) & (sd > 1e-12)
            Xv = Xm[:, valid]
            if Xv.shape[1] < 2:
                detail_rows.append({"donor_id": donor, "n_cells": len(row_idx), "m": m,
                                    "m_nonconstant": Xv.shape[1], "rank": 0,
                                    "effective_rank": np.nan, "min_eigenvalue": np.nan,
                                    "max_eigenvalue": np.nan, "condition_number": np.inf})
                continue
            C = np.corrcoef(Xv, rowvar=False)
            C = 0.5 * (C + C.T)
            np.fill_diagonal(C, 1.0)
            eig = np.linalg.eigvalsh(C)
            pos = eig[eig > args.rank_tol]
            cond = float(eig[-1] / pos[0]) if len(pos) else np.inf
            detail_rows.append({
                "donor_id": donor, "n_cells": len(row_idx), "m": m,
                "m_nonconstant": int(Xv.shape[1]),
                "rank": int(np.sum(eig > args.rank_tol)),
                "effective_rank": effective_rank(eig),
                "min_eigenvalue": float(eig[0]),
                "max_eigenvalue": float(eig[-1]),
                "condition_number": cond,
            })
        if di == 1 or di % 20 == 0 or di == len(donor_names):
            print(f"[SWEEP] donors {di}/{len(donor_names)}")

    detail = pd.DataFrame(detail_rows)
    detail.to_csv(args.output_dir / "dimensionality_sweep_by_donor.csv", index=False)

    stability_path = args.gene_selection_dir / "ranking_stability.csv"
    stab = pd.read_csv(stability_path) if stability_path.exists() else pd.DataFrame()

    rows = []
    for m, g in detail.groupby("m"):
        full_rank_fraction = float(np.mean(g["rank"].to_numpy() == g["m_nonconstant"].to_numpy()))
        nonconstant_fraction = float(np.mean(g["m_nonconstant"].to_numpy() == m))
        min_eig_all = float(np.nanmin(g["min_eigenvalue"]))
        cond_max = float(np.nanmax(g["condition_number"]))
        qmax = float(m / nmin)

        stab_mean = np.nan
        if not stab.empty:
            ss = stab[(stab["method"] == "variance") & (stab["m"] == m)]
            if len(ss):
                stab_mean = float(ss.iloc[0]["mean"])

        passes = (
            (qmax <= args.q_threshold)
            and (np.isnan(stab_mean) or stab_mean >= args.stability_threshold)
            and (nonconstant_fraction == 1.0)
            and (full_rank_fraction == 1.0)
            and (min_eig_all >= -args.eig_tol)
            and (cond_max <= args.condition_threshold)
        )
        rows.append({
            "m": int(m),
            "n_min_cells": nmin,
            "q_max": qmax,
            "stability_mean_jaccard": stab_mean,
            "nonconstant_all_donors": bool(nonconstant_fraction == 1.0),
            "full_rank_all_donors": bool(full_rank_fraction == 1.0),
            "effective_rank_median": float(np.nanmedian(g["effective_rank"])),
            "effective_rank_fraction_median": float(np.nanmedian(g["effective_rank"] / m)),
            "min_eigenvalue_worst": min_eig_all,
            "condition_number_median": float(np.nanmedian(g["condition_number"])),
            "condition_number_max": cond_max,
            "passes_prespecified_rules": bool(passes),
        })

    summary = pd.DataFrame(rows).sort_values("m")
    summary.to_csv(args.output_dir / "dimensionality_sweep_summary.csv", index=False)

    passing = summary[summary["passes_prespecified_rules"]]
    if len(passing):
        recommended = int(passing["m"].max())
        statement = f"recommended_m={recommended} (largest tested m satisfying all prespecified rules)"
    else:
        recommended = None
        statement = "recommended_m=NONE (no tested m satisfied all prespecified rules)"

    text = [
        "SLE DIMENSIONALITY SWEEP",
        "Ranking fixed a priori: donor-balanced variance",
        "Disease labels not used.",
        f"n_donors={len(donor_names)}",
        f"minimum_cells_per_donor={nmin}",
        f"q_threshold={args.q_threshold}",
        f"stability_threshold={args.stability_threshold}",
        f"condition_number_threshold={args.condition_threshold}",
        statement,
        "",
        "Selection rule: choose the largest tested m satisfying simultaneously:",
        "1) q_max <= threshold;",
        "2) mean donor-resampling Jaccard >= threshold when available;",
        "3) all selected genes nonconstant in every donor;",
        "4) full-rank correlation matrix for every donor;",
        "5) PSD within numerical tolerance;",
        "6) maximum condition number <= threshold.",
    ]
    (args.output_dir / "dimensionality_recommendation.txt").write_text("\n".join(text), encoding="utf-8")
    print("\n".join("[RESULT] " + x for x in text if x))
    print(summary.to_string(index=False))

    if a.file is not None:
        a.file.close()


if __name__ == "__main__":
    main()
